
Before Procedure Add:

Theory: 

In this project you will classify five different stars according to the
Harvard classification scheme 

   O B A F G K M

The description of different classes is given below:

The $O$ type stars are very hot and bluish in color. Their surface temperature
ranges from 40000 K to 20000 K. Due to the high temperature they show
strong absorption and sometimes emission lines from different ions such
as HeII, CIII, NIII, OIII, SiIV and SiV as well as from neutral Helium
atom HeI. The HI Balmer lines are visible but weak. An example of this star 
which can be seen by naked eye is Meissa which lies in the constellation Orion.

 

The $B$ type stars are also very hot with surface temperature ranging from 20000K to 10000 K. 
They are also blue in color. Their spectra show neutral Helium
lines, which are strongest at $B2$. One also sees lines from ions such as
OII, SiII, MgII. The HI Balmer lines are relatively strong.
A naked eye example of a $B$ type star is Rigel, which is the brightest star
in constellation Orion.


The $A$ type stars are white in color and have surface temperature ranging from 
10000 K to 7500 K. These have very strong hydrogen HI lines. One also sees
lines of ions such as MgII, SiII. The CaII lines are also seen but weak. 
A naked eye example of an $A$ type star is Sirius in constellation Canis Major, 
which is the brightest star in night sky.

The $F$ type stars have surface temperature in the range 7500 K to 6000 K
and have a yellow-white color. The HI lines are getting weaker but still
relatively strong. CaII and FeII lines start getting stronger. Neutral 
metal lines (FeI) and CaI also becoming visible. An example is Canopus in
constellation Carina. It is the second brightest star in the night sky. 

The $G$ type are yellow stars with surface temperature roughly in the 
range 6000 K to 4500 K. Here the HI lines are weak. CaII lines continue to 
become stronger. FeII lines strong. FeI, CaI lines becoming stronger. 
Sun is a $G2$ type star. Another example is Alpha Centauri A in constellation
Centaurus. 

The $K$ type are orange stars with surface temperature in the range 4500 K
to 3600 K. The HI lines are now very weak. The spectrum
is dominated by metal absorption lines. CaII lines very strong. The
neutral metal lines FeI, SiI visible. The molecular bands of TiO
 become visible by $K5$. An example is Aldebaran in the constellation Taurus.

The $M$ type stars are cool red stars with surface temperature less than 3600
K. Here the spectra is dominated by TiO bands and neutral metal (FeI) lines.
The HI lines are absent. CaI lines are also very strong. An example is 
Betelgeuse in the constellation Orion. 

A spectral plot of Sun along with identification of several lines is shown
in figure ...
phot-44d-98-preview.jpg
 
A useful link for
stellar classification is
\begin{verbatim}
http://en.wikipedia.org/wiki/Stellar_classification
\end{verbatim} 

Examples of stellar spectra corresponding to each of these classes
is available at,
\begin{verbatim}
http://nedwww.ipac.caltech.edu/level5/ASS_Atlas/frames.html
\end{verbatim}


--=-QpXcq+9FU5373R7eAC8E
Content-Type: image/jpeg; name="phot-44d-98-preview.jpg"
Content-Disposition: attachment; filename="phot-44d-98-preview.jpg"
Content-Transfer-Encoding: base64



--=-QpXcq+9FU5373R7eAC8E--


