Return-Path: <pkjain@iitk.ac.in>
X-Original-To: purnendu@iitk.ac.in
Delivered-To: purnendu@iitk.ac.in
Received: from mail2.iitk.ac.in (mail2.iitk.ac.in [172.31.1.214])
	by newmailhost.cc.iitk.ac.in (Postfix) with ESMTP id 39336712B38
	for <purnendu@iitk.ac.in>; Wed, 18 Jan 2012 18:24:13 +0530 (IST)
Received: from smtp.cc.iitk.ac.in (smtp.cc.iitk.ac.in [172.31.1.22])
	by mail2.iitk.ac.in (Postfix) with ESMTP id 839A710000AF
	for <purnendu@iitk.ac.in>; Wed, 18 Jan 2012 18:24:20 +0530 (IST)
Received: from [172.28.37.14] (unknown [172.28.37.14])
	(Authenticated sender: pkjain)
	by smtp.cc.iitk.ac.in (Postfix) with ESMTPA id 9EA5D42
	for <purnendu@iitk.ac.in>; Wed, 18 Jan 2012 18:24:17 +0530 (IST)
Message-ID: <1326891202.2764.4.camel@cosmic>
Subject: search
From: Pankaj Jain <pkjain@iitk.ac.in>
Reply-To: pkjain@iitk.ac.in
To: purnendu <purnendu@iitk.ac.in>
Date: Wed, 18 Jan 2012 18:23:22 +0530
Content-Type: text/plain
X-Mailer: Evolution 3.2.1- 
Content-Transfer-Encoding: 7bit
Mime-Version: 1.0

strength of spectral lines from stars 
images


